[package]
name = "test_ggez"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
image = "0.23.14"
scrap = "0.5.0"