name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fmt
      run: cargo fmt -- --check
      
  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-clippy
      run: rustup component add clippy
    - name: clippy
      run: cargo clippy -- -W clippy::pedantic
      
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
